language: php

php:
    - 8.0

install:
    - composer install -n --ignore-platform-reqs --no-suggest

script:
    - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash -t ${{ secrets.CODECOV_TOKEN }})
